FROM alpine
RUN apk add --no-cache python3 py3-pip
RUN pip install flask
RUN pip install requests
RUN pip install flask-cors
RUN pip install flask-restful

# Path: /app
WORKDIR /app
COPY . /app
COPY requirements.txt /app
RUN pip install -r requirements.txt
EXPOSE 5000